service: nestjs-cart-service

provider:
  name: aws
  runtime: nodejs18.x
  stage: dev
  region: eu-west-1
  environment:
    DB_HOST: ${env:DB_HOST}
    DB_DATABASE: ${env:DB_DATABASE}
    DB_USERNAME: ${env:DB_USERNAME}
    DB_PASSWORD: ${env:DB_PASSWORD}
    DB_PORT: ${env:DB_PORT}
    SERVERLESS: true

functions:
  app:
    handler: dist/main.handler
    events:
      - http:
          path: /
          method: any
      - http:
          path: '{proxy+}'
          method: any

plugins:
  - serverless-offline

package:
  individually: true
  exclude:
    - node_modules/**
  include:
    - dist/**
